name: jaguar_validate
description: A super simple fluent Validator framework for Dart
version: 1.0.0
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <2.0.0"

# dependencies:

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
