name: jaguar_validate
description: A configurable and extensible validation framework that supports validation of objects (nested), arrays. Supports error code and parameter support for translation.
version: 2.0.6
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_validate

environment:
  sdk: ">=2.4.0 <3.0.0"

# dependencies:

dev_dependencies:
  test: ^1.3.0
  pedantic: ^1.9.0