name: jaguar_validate
description: A super simple fluent Validator framework for Dart
version: 2.0.0
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.4.0 <3.0.0"

# dependencies:

dev_dependencies:
  test: ^1.3.0
