name: jaguar_validate
description: A configurable and extensible validation framework for Dart that supports validation of objects (nested), arrays and primitive types. Supports error code and parameter support for translation.
version: 2.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.4.0 <3.0.0"

# dependencies:

dev_dependencies:
  test: ^1.3.0
  pedantic: ^1.9.0